{% set name = "xhydro" %}
{% set version = "0.9.0" %}
{% set python_min = "3.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/xhydro-{{ version }}.tar.gz
  sha256: 493c3ef3342d275afb927f78e2e9717f4bcc7145cec6988228fa2b2cbd9bc7ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.12.0,<4
    - pip >=25.2
  run:
    - python >={{ python_min }}
    - cartopy >=0.23.0
    - clisops
    - dask
    - dask-geopandas
    - fastprogress <1.1 # FIXME: Temporary fix following https://github.com/intake/intake-esm/pull/773. Remove when intake-esm (via xscen) is updated.
    - geopandas >=1.0
    - haversine >=2.8.1
    - leafmap
    - mapclassify  # Hidden dependency needed to extract watershed delineation using leafmap objects
    - matplotlib-base
    - numpy >=1.25
    - odc-stac
    - pandas >=2.2,!=3.0.4
    - planetary-computer
    - pooch >=1.8.0
    - pystac >=1.12.0
    - pystac-client
    - pyyaml >=6.0.2
    - rasterio
    - ravenpy >=0.18.1
    - rioxarray >=0.15.0
    - scikit-learn
    - scipy >=1.12.0
    - shapely >=2.0
    - spotpy >=1.6.2
    - statsmodels >=0.14.0
    - tqdm
    - xarray >=2023.11.0
    - xarray-spatial >=0.3.7
    - xclim
    - xscen >=0.12.1,<0.16
    - xvec
  run_constrained:
    - juliacall >=0.9.20
    - juliapkg >=0.1.19
    - xdatasets >=0.3.9

test:
  imports:
    - xhydro
  commands:
    # - pip check # PyCRS gives a false positive here
    - pytest tests
  requires:
    - python {{ python_min }}
    - pip >=25.2
    - lmoments3 >=1.0.7  # needed for test_regional.py
    - pytest >=9.0.2
    - python-dotenv >=1.2.1
    - pytest-xdist >=3.2.0
    - requests
    - xdatasets >=0.3.9  # needed for test_gis.py
  source_files:
    - CHANGELOG.rst
    - pyproject.toml
    - tests

about:
  home: https://github.com/hydrologie/xhydro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Hydrological analysis library built with xarray.
  dev_url: https://github.com/hydrologie/xhydro
  doc_url: https://xhydro.readthedocs.io

extra:
  recipe-maintainers:
    - RondeauG
    - sebastienlanglois
    - Zeitsperre
